project: default
source:
  repoURL: 'https://bjw-s.github.io/helm-charts'
  targetRevision: 3.1.0
  helm:
    valueFiles:
      - values.yaml
  chart: app-template
destination:
  server: 'https://kubernetes.default.svc'
  namespace: arr
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace = true
