apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-ingress
  namespace: longhorn-system
spec:
  entryPoints:
    - websecure
    - web
  routes:
    - kind: Rule
      match: Host(`longhorn.kube.007337.xyz`)
      middlewares:
        - name: authentik
          namespace: kube-system
      services:
        - name: longhorn-frontend
          port: 80
