apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ .Release.Name }}-ingress"
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
    - web
  routes:
    - kind: Rule
      match: Host(`{{ .Release.Name }}.media.007337.xyz`)
      middlewares:
        - name: authentik
          namespace: {{ .Release.Namespace }}
      services:
        - name: {{ .Release.Name }}
          port: {{ .Values.service.main.ports.http.port }}
    - kind: Rule
      match: Host(`{{ .Release.Name }}.media.007337.xyz`) && PathPrefix(`/outpost.goauthentik.io/`)"
      priority: 15
      services:
        - kind: Service
          name: ak-outpost-k3s-proxy-outpost
          port: 9000