apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ .Values.service.main.nameOverride }}-ingress"
  namespace: media
spec:
  entryPoints:
    - websecure
    - web
  routes:
    - kind: Rule
      {{- with (index .Values.ingress.main.hosts 0) }}
      match: Host(`{{ .host }}`)
      middlewares:
        - name: authentik
          namespace: media
      services:
        - name: {{ .Values.service.main.nameOverride }}-service
          port: {{ .Values.service.main.ports.http.port }}
    - kind: Rule
      match: Host(`{{ .host }}`) && PathPrefix(`/outpost.goauthentik.io/`)"
      priority: 15
      services:
        - kind: Service
          name: ak-outpost-k3s-proxy-outpost
          port: 9000
{{- end }}