- hosts: almalinux
  become: yes
  tasks:
    - name: ensure Basic tools are installed
      dnf:
        name: 
          - dnf-plugins-core
          - nano
        state: present

    - name: Install epel-release
      dnf:
        name: epel-release
        state: present

    - name: Update all packages
      ansible.builtin.dnf:
        name: '*'
        state: latest

    - name: Autoremove unneeded packages installed as dependencies
      ansible.builtin.dnf:
        autoremove: yes

    - name: Add the user 'james' with a bash shell, appending the group 'admins' and 'developers' to the user's groups
      ansible.builtin.user:
        name: maxid
        shell: /bin/bash
        groups: wheel
        append: yes

    - name: Set authorized keys taken from url
      ansible.posix.authorized_key:
        user: maxid
        state: present
        key: https://github.com/CookieDude24.keys


    - name: reboot if requiered
      ansible.builtin.command: needs-restarting -r
      register: reboot_required
      failed_when: false
      changed_when: reboot_required.rc != 0
      notify:
          - Reboot Almalinux

  handlers:
      - name: Reboot Almalinux
        ansible.builtin.reboot:
            msg: "Reboot initiated by Ansible"
            reboot_timeout: 3600
            test_command: w