- hosts: almalinux
  become: yes
  tasks:
    - name: ensure Basic tools are installed
      dnf:
        name: 
          - dnf-plugins-core
          - nano
        state: present

    - name: Install epel-release
      dnf:
        name: epel-release
        state: present

    - name: Update all packages
      ansible.builtin.dnf:
        name: '*'
        state: latest

    - name: Autoremove unneeded packages installed as dependencies
      ansible.builtin.dnf:
        autoremove: yes

    - name: reboot if requiered
      ansible.builtin.command: needs-restarting -r
      register: reboot_required
      failed_when: false
      changed_when: reboot_required.rc != 0
      notify:
          - Reboot Almalinux

  handlers:
      - name: Reboot Almalinux
        ansible.builtin.reboot:
            msg: "Reboot initiated by Ansible"
            reboot_timeout: 3600
            test_command: w