- hosts: fedora:&k3s
  become: yes
  tasks:
    - name: install all necessary packages
      dnf:
        name: 
          - open-iscsi
          - curl
          - nfs-common
          - jq
          - qemu-guest-agent
          - linux-crashdump
          - snapd
        state: present

    - name: Install all necessary snaps
      community.general.snap:
        name:
          - helm
          - kubectl
        classic: true
      
    - name: start iscuzzy service
      ansible.builtin.systemd_service:
        name: iscsid
        state: started
        enabled: true

    - name: start qemu agent
      ansible.builtin.systemd_service:
        name: qemu-guest-agent
        state: started
        enabled: true

    - name: Create a ext4 filesystem on /dev/sdb1 and check disk blocks
      community.general.filesystem:
        fstype: ext4
        dev: /dev/sdb
        opts: -cc

    - name: Mount sdb
      mount:
        path: /var/longhorn
        src: /dev/sdb
        fstype: ext4
        state: present

    - name: reboot if requiered
      ansible.builtin.command: needs-restarting -r
      register: reboot_required
      failed_when: false
      changed_when: reboot_required.rc != 0
      notify:
        - rebooting

  handlers:
    - name: Reboot Almalinux
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible"
        reboot_timeout: 3600