controllers:
  main:
    containers:
      main:
        env:
          TZ: Etc/UTC
        image:
          pullPolicy: Always
          repository: ghcr.io/ajnart/homarr
          tag: latest
    strategy: Recreate
ingress:
  main:
    hosts:
      - host: homarr.kube.007337.xyz
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
persistence:
  config:
    accessMode: ReadWriteOnce
    enabled: true
    size: 1Gi
    type: persistentVolumeClaim
    globalMounts:
      - path: /app/data/configs
      - path: /app/public/icons
      - path: /data
service:
  main:
    controller: main
    ports:
      http:
        port: 7575
    type: ClusterIP
