controllers:
  main:
    containers:
      main:
        env:
          TZ: Etc/UTC
          UN_SONARR_0_URL: http://sonarr.media.svc.cluster.local:8989
          UN_SONARR_0_API_KEY:
            valueFrom:
              secretKeyRef:
                name: arr-api-keys
                key: sonarr-api-key
          UN_SONARR_0_PATHS_0: /data/downloads
          UN_RADARR_0_URL: http://radarr.media.svc.cluster.local:7878
          UN_RADARR_0_API_KEY:
            valueFrom:
              secretKeyRef:
                name: arr-api-keys
                key: radarr-api-key
          UN_RADARR_0_PATHS_0: /data/downloads
        image:
          pullPolicy: Always
          repository: golift/unpackerr
          tag: latest
    strategy: Recreate
persistence:
  data:
    enabled: true
    path: /pool0/media/
    server: 192.168.1.91
    type: nfs
    globalMounts:
        - path: /data/downloads
