controllers:
  main:
    containers:
      main:
        image:
          pullPolicy: Always
          repository: louislam/uptime-kuma
          tag: 1
    strategy: Recreate
ingress:
  main:
    hosts:
      - host: uptime.007337.xyz
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
service:
  main:
    controller: main
    ports:
      http:
        port: 3001
    type: ClusterIP
persistence:
  app:
    accessMode: ReadWriteOnce
    globalMounts:
      - path: /app/data
    size: 5Gi
    type: persistentVolumeClaim