---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: arr-api-keys
  namespace: media
spec:
  encryptedData:
    radarr-api-key: AgBAt9WFo8km6mMsnRL7bygaZ3BPhKwM9U2JjZF7Fk2JPOzy+hh7Ql03t0JX5pUTZwz9cPQx1o2iVfB4Qv1J5pwHCFUhTeq2zkTxG6l/KsZx7zyPtmGdkBZwJ3mF3/PPWMDU4HfpgpVNDVt31tR5pZO35pb5EyKCKmovs67gQyBsPhqvtYYKh4B7vQuFnjIu22ROtdZsEdrJyCJP9zaq32XWj7aUvyh1TcQazyoVBIE38lWADKygzLbrwEBaKC9nyzCNDIKKJNKiAYCznGLP/O0JI90uK0l1AcamF0IHLTr1Ty5Nz1dtWIwqpE5YfisxOgEdJd8+0XRKSzfAPYkQN8Q3yV0VJ+hzkEDNrJxvg/Qjv/1gxK6ZsZjcj1xSnkIQDkvqVk6WIoTP28rRGZz8prBXHhK/7dNO9+9tAoVXbHeOkw4SpdqbQaehy8qo+I2FJSQiI1HGc42twfcpa/X8g4cWF3SODFRYqwJEutF6TEP01CqwCVATIVYp3iz6t3qIgd4pLJDsLhoY4cSuPKFcSwGQqdMNeFZh9a4ExU3j/GrdIglBf2GLtF3zUhZ8x+Nv0dryCLS9NgEqFOIPXdjeJmuGr4NU5d2ssDj2mHV5Kh/kgq42PE69oDYQbd/YEc8gA6NpYVH3xoIyAt5vtYRQSprSQG/W7Dc0FAao39Zqz55BFKAh4rBCEASF+MxF/wYCjTlz2lMKKTQVY7ZdOrRGB9eZtJVVKEv6jPXn58OenCGxYg==
    sonarr-api-key: AgBaBgHRNOo7QsEgYB5CyglFMFaHeh/WUoNahMH3x33OuRq5i4SM2XO//gZP8g+iTQpkIpW0JNkZ0+xGBrdGFg3wElowxRLBD0fdk33WTc3lK49L/YvtGxSUjrcq7YKL+fU2eP6t7hdY72ASgd9CMeW4y6sLDiRHnbECjHGq9r8H9Y64z/Pc5RrZ1K/BAqov7QFJqE1V8DWzyUFvNaMF6zGpSaULJfD9gNwBbQlb2c0fCE2o+iOaZpzoxln2V+XBqDOdee6sDMzPwLaMRUHLCxS3Lr8e05SFRIkvj8x5ilq48v5gk8pdGEyXSOv+8lwxjY8dvqqhdlXG29z89eeQrTXhas6GX0M1UMwoVm0VnRuimbFQz+2bq9HOzlC42uSJdXVo+svjow9mMwiZvhtg/N7eMUoiGsyPqzXTC8WdfpluHiClyJQEFL3H1kR49rPfF4qPjsgiBh9lduVYvxS684NvwUKMTuw+43YtieJa9Lhci2JXRKhdN6WHXyEwAtHOzRjTF45idLL5dRPXlVnf9DG0Dnuk9yHh/8HGY4EL5cPt+pW/8dUN9yczO+kEcOlNNgJ9yLneEvauzHORpAoguUrbrQkjtwyLGEGx/NxR0FhPmWXlkzrsh4Fb5QKD3spwWjPzJ/f1YUki9/AqiLy5ghft9DGpcz7w+DuJmMpjszYIIvf3nU1RbMjdKe9rWjaM93IgGq64YB+zILWqotOCTftyV3gP/+/0+z/p0+I2m3s5HQ==
  template:
    metadata:
      creationTimestamp: null
      name: arr-api-keys
      namespace: media