service:
  main:
    controller: main
    ports:
      http:
        port: &port 8080
        protocol: HTTP
    nameOverride: qbittorrent
  bittorrent:
    enabled: true
    controller: main
    type: LoadBalancer
    loadBalancerIP: 192.168.1.121
    ports:
      bittorrent-tcp:
        enabled: true
        port: 6881
        protocol: TCP
        targetPort: 6881
      bittorrent-udp:
        enabled: true
        port: 6881
        protocol: UDP
        targetPort: 6881
controllers:
  main:
    type: statefulset

    statefulset:
      volumeClaimTemplates:
        - name: config
          globalMounts:
            - path: /config
          storageClass: longhorn
          accessMode: ReadWriteOnce
          size: 1Gi
    containers:
      main:
        env:
          TZ: Etc/UTC
          WEBUI_PORT: *port
        image:
          pullPolicy: Always
          repository: lscr.io/linuxserver/qbittorrent
          tag: latest
        probes:
          liveness:
            enabled: true
            custom: true
            type: HTTP
            spec:
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
              httpGet:
                path: /
                port: *port

          readiness:
            enabled: true
            custom: true
            type: HTTP
            spec:
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
              httpGet:
                path: /
                port: *port

persistence:
  data:
    enabled: true
    path: /pool0/media/
    server: 192.168.1.91
    type: nfs

