service:
  main:
    controller: main
    ports:
      http:
        port: &port 8080
        protocol: HTTP
      torrenttcp:
        port: 6881
        protocol: TCP
      torrentudp:
        port: 6881
        protocol: UDP
    type: ClusterIP
controllers:
  main:
    containers:
      main:
        env:
          TZ: Etc/UTC
          WEBUI_PORT: 8080
        image:
          pullPolicy: Always
          repository: lscr.io/linuxserver/qbittorrent
          tag: latest
      probes:
        liveness:
          enabled: true
          custom: true
          type: HTTP
          spec:
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
            httpGet:
              path: /
              port: *port

        readiness:
          enabled: true
          custom: true
          type: HTTP
          spec:
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
            httpGet:
              path: /
              port: *port

        startup:
          enabled: true
          custom: false
          type: HTTP
          spec:
            initialDelaySeconds: 0
            timeoutSeconds: 1
            periodSeconds: 5
            failureThreshold: 30
            httpGet:
              path: /
              port: *port
persistence:
  config:
    accessMode: ReadWriteMany
    enabled: true
    size: 1Gi
    type: persistentVolumeClaim
  data:
    enabled: true
    path: /pool0/media/
    server: 192.168.1.91
    type: nfs

