controllers:
  main:
    containers:
      main:
        env:
          TZ: Etc/UTC
          ND-BASEURL: /navidrome
          ND_SCANSCHEDULE: 1h
          ND_LOGLEVEL: info
          ND_SESSIONTIMEOUT: 24h
        image:
          pullPolicy: Always
          repository: deluan/navidrome
          tag: latest
    strategy: Recreate
ingress:
  main:
    hosts:
      - host: media.007337.xyz
        paths:
          - path: /navidrome
            pathType: Prefix
            service:
              identifier: main
              port: http
    tls:
      - secretName: media-007337-xyz
        hosts:
          - media.007337.xyz
persistence:
  config:
    accessMode: ReadWriteOnce
    enabled: true
    size: 5Gi
    type: persistentVolumeClaim
  data:
    enabled: true
    path: /pool0/media/music
    server: nfs.home.007337.xyz
    type: nfs
    globalMounts:
      - path: /music/music
service:
  main:
    controller: main
    ports:
      http:
        port: 4533
    type: ClusterIP
