controllers:
  main:
    containers:
      main:
        env:
          TZ: Etc/UTC
        image:
          pullPolicy: Always
          repository: lscr.io/linuxserver/radarr
          tag: latest
ingress:
  main:
    hosts:
      - host: media.007337.xyz
        paths:
          - path: /radarr
            pathType: Prefix
            service:
              identifier: main
              port: http
    tls:
      - secretName: media-007337-xyz
        hosts:
          - media.007337.xyz
persistence:
  config:
    accessMode: ReadWriteOnce
    globalMounts:
      - path: /config
    size: 1Gi
    type: persistentVolumeClaim
  data:
    enabled: true
    path: /pool0/media/
    server: nfs.home.007337.xyz
    type: nfs
service:
  main:
    nameOverride: "radarr"
    controller: main
    ports:
      http:
        port: 7878
    type: ClusterIP
