controllers:
  main:
    containers:
      main:
        env:
          TZ: Etc/UTC
        image:
          pullPolicy: Always
          repository: lscr.io/linuxserver/radarr
          tag: latest
persistence:
  config:
    accessMode: ReadWriteOnce
    globalMounts:
      - path: /config
    size: 1Gi
    type: persistentVolumeClaim
  data:
    enabled: true
    path: /pool0/media/
    server: nfs.home.007337.xyz
    type: nfs
service:
  main:
    controller: main
    ports:
      http:
        port: 7878
    type: ClusterIP
