service:
  main:
    controller: main
    ports:
      http:
        port: &port 7878
    type: ClusterIP
controllers:
  main:
    type: statefulset

    statefulset:
      volumeClaimTemplates:
        - name: config
          globalMounts:
            - path: /config
          storageClass: longhorn
          accessMode: ReadWriteOnce
          size: 1Gi

    pod:
      securityContext:
        runAsUser: 1001
        runAsGroup: &group 1001
        fsGroup: *group
        fsGroupChangePolicy: "OnRootMismatch"

    containers:
      main:
        env:
          TZ: Etc/UTC
          RADARR__AUTHENTICATION_REQUIRED: DisabledForLocalAddresses
          RADARR__AUTHENTICATION_METHOD: External
          RADARR__API_KEY:
            valueFrom:
              secretKeyRef:
                name: arr-api-keys
                key: radarr-api-key

        image:
          pullPolicy: IfNotPresent
          repository: ghcr.io/onedr0p/radarr
          tag: 5.6.0.8846

        probes:
          liveness: &probe
            enabled: true
            custom: true
            type: HTTP
            spec:
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
              httpGet:
                path: &path /ping
                port: *port

          readiness: *probe

          startup:
            enabled: true
            custom: true
            type: HTTP
            spec:
              initialDelaySeconds: 0
              timeoutSeconds: 1
              periodSeconds: 5
              failureThreshold: 30
              httpGet:
                path: *path
                port: *port
persistence:
  data:
    enabled: true
    path: /var/storage/media/
    server: nfs.007337.xyz
    type: nfs

