apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unpackerr
  namespace: arr
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: unpackerr
    repoURL: https://github.com/CookieDude24/kubernetes.git
    targetRevision: HEAD