apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: app-of-apps
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    path: app-of-apps
    repoURL: https://github.com/CookieDude24/kubernetes.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  project: default