apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-cd-argocd-server
  namespace: argocd
spec:
  ingressClassName: traefik
  rules:
    - host: kube.007337.xyz
      http:
        paths:
          - backend:
              service:
                name: argocd-server
                port:
                  number: 80
            path: /argocd
            pathType: Prefix