apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
        allowExternalNameServices: true
        enabled: true
      kubernetesIngress:
        publishedService:
          enabled: true
        allowExternalNameServices: true
        enabled: true