controllers:
  main:
    containers:
      main:
        env:
          TZ: Etc/UTC
        image:
          pullPolicy: Always
          repository: ghcr.io/hotio/unpackerr
          tag: latest
    strategy: Recreate
persistence:
  config:
    accessMode: ReadWriteOnce
    globalMounts:
      - path: /config
    size: 1Gi
    type: persistentVolumeClaim
  data:
    enabled: true
    path: /pool0/media/
    server: nfs.home.007337.xyz
    type: nfs