---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homeassistant-ingress
  namespace: default

spec:
  entryPoints:
    - websecure
    - web

  routes:
    - match: Host(`home.007337.xyz`)
      kind: Rule
      services:
        - name: homeassistant
          port: 8123

---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  namespace: default
spec:
  externalName: 192.168.1.80
  type: ExternalName
  ports:
    - port: 8123