---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: immich-ingress
  namespace: media

spec:
  entryPoints:
    - websecure
    - web

  routes:
    - match: Host(`immich.media.007337.xyz`)
      kind: Rule
      services:
        - name: immich
          port: 2283

---
apiVersion: v1
kind: Service
metadata:
  name: immich
  namespace: media
spec:
  externalName: 192.168.1.86
  type: ExternalName
  ports:
    - port: 2283