---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: semaphore-ingress
  namespace: default

spec:
  entryPoints:
    - websecure
    - web

  routes:
    - match: Host(`kube.007337.xyz`) && PathPrefix(`/semaphore`)
      kind: Rule
      services:
        - name: semaphore
          port: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: semaphore
  namespace: default
spec:
  externalName: 192.168.1.85
  type: ExternalName
  ports:
    - port: 3000