service:
  main:
    controller: main
    ports:
      http:
        port: &port 8989
    type: ClusterIP
controllers:
  main:
    strategy: RollingUpdate

    pod:
      securityContext:
        runAsUser: 1100
        runAsGroup: &group 1100
        fsGroup: *group
        fsGroupChangePolicy: "OnRootMismatch"

    containers:
      main:
        env:
          TZ: Etc/UTC
          SONARR__AUTHENTICATION_REQUIRED: DisabledForLocalAddresses
          SONARR__AUTHENTICATION_METHOD: External
          SONARR__API_KEY:
            valueFrom:
              secretKeyRef:
                name: arr-api-keys
                key: sonarr-api-key

        image:
          pullPolicy: IfNotPresent
          repository: ghcr.io/onedr0p/sonarr
          tag: 4.0.4

        probes:
          liveness: &probe
            enabled: true
            custom: true
            type: HTTP
            spec:
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
              httpGet:
                path: &path /ping
                port: *port

          readiness: *probe

          startup:
            enabled: true
            custom: true
            type: HTTP
            spec:
              initialDelaySeconds: 0
              timeoutSeconds: 1
              periodSeconds: 5
              failureThreshold: 30
              httpGet:
                path: *path
                port: *port

persistence:
  data:
    enabled: true
    path: /var/storage/media/
    server: nfs.007337.xyz
    type: nfs

  config:
    enabled: true
    path: /var/storage/media/container-data/sonarr
    server: nfs.007337.xyz
    type: nfs

