apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes/infrastructure/argocd
    repoURL: https://github.com/CookieDude24/kubernetes.git
    targetRevision: HEAD