apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik-remote-clusters
  namespace: argocd
spec:
  destination:
    namespace: authentik
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: authentik-remote-cluster
    helm:
      parameters:
        - name: installCRDs
          value: "true"
    repoURL: https://charts.goauthentik.io/
    targetRevision: 2.0.0