apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certificates
  namespace: cert-manager
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: certificates
    repoURL: https://github.com/CookieDude24/kubernetes.git
    targetRevision: HEAD
