apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: arr
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: kubernetes/media/jellyfin
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: {{ .Values.spec.automated.prune }}
      selfHeal: {{ .Values.spec.automated.selfHeal }}
