apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.6.1
      helm:
        values: |
          defaultSettings:
            defaultDataPath: /dev/sdb
            backupTarget: nfs://nfs.home.007337.xyz:/var/storage/backup/longhorn/
          preUpgradeChecker:
            jobEnabled: false
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: longhorn-system