apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paperless-ngx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: paperless
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: kubernetes/apps/paperless-ngx
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: {{ .Values.spec.automated.prune }}
