service:
  main:
    controller: main
    ports:
      http:
        port: &port 9000
    type: ClusterIP
controllers:
  main:
    strategy: Recreate
    containers:
      main:
        env:
          TZ: Europe/Vienna
          ALLOW_SIGNUP: true
          OIDC_AUTH_ENABLED: true
          OIDC_SIGNUP_ENABLED: true
          OIDC_USER_GROUP: Users
          OIDC_ADMIN_GROUP: Admins
          OIDC_CONFIGURATION_URL: https://auth.007337.xyz/application/o/mealie/.well-known/openid-configuration
          OIDC_CLIENT_ID:
            valueFrom:
              secretKeyRef:
                name: mealie-authentik-sso-secret
                key: client-id
          OIDC_REMEMBER_ME: true
          OIDC_SIGNING_ALGORITHM: ES256
          OIDC_PROVIDER_NAME: Authentik
          OIDC_AUTO_REDIRECT: true
          OIDC_GROUPS_CLAIM: groups
          BASE_URL: https://007337.xyz/mealie
          MAX_WORKERS: 1
          WEB_CONCURRENCY: 1
        image:
          pullPolicy: IfNotPresent
          repository: ghcr.io/mealie-recipes/mealie
          tag: v1.7.0
        probes:
          probes:
            liveness: &probe
              enabled: true
              custom: true
              type: HTTP
              spec:
                initialDelaySeconds: 0
                periodSeconds: 10
                timeoutSeconds: 1
                failureThreshold: 3
                httpGet:
                  path: &path /health
                  port: *port

            readiness: *probe

            startup:
              enabled: true
              custom: true
              type: HTTP
              spec:
                initialDelaySeconds: 0
                timeoutSeconds: 1
                periodSeconds: 5
                failureThreshold: 30
                httpGet:
                  path: *path
                  port: *port
persistence:
  data:
    globalMounts:
      - path: /app/data
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 1Gi