- hosts: fedora:&fileserver
  become: yes
  tasks:
    - name: install essential necessary packages
      dnf:
        name:
          - curl
          - wget
          - qemu-guest-agent
          - dnf-utils
        state: present

    - name: install all necessary packages for nfs
      dnf:
        name:
          - nfs-utils
        state: present

    - name: install all necessary packages for smb
      dnf:
        name:
          - samba
          - samba-client
          - samba-common
          - cifs-utils
        state: present

    - name: start qemu agent
      ansible.builtin.systemd_service:
        name: qemu-guest-agent
        state: started
        enabled: true

    - name: start smb-server
      ansible.builtin.systemd_service:
        name: smb
        state: started
        enabled: true

    - name: start nfs-server
      ansible.builtin.systemd_service:
        name: nfs-server
        state: started
        enabled: true

    - name: start rpcbind
      ansible.builtin.systemd_service:
        name: rpcbind
        state: started
        enabled: true

    - name: start rpc-statd
      ansible.builtin.systemd_service:
        name: rpc-statd
        state: started
        enabled: true

    - name: start nfs-idmapd
      ansible.builtin.systemd_service:
        name: nfs-idmapd
        state: started
        enabled: true

    - name: Create a ext4 filesystem on /dev/sdb1 and check disk blocks
      community.general.filesystem:
        fstype: ext4
        dev: /dev/sdb

    - name: Mount sdb
      mount:
        path: /var/storage
        src: /dev/sdb
        fstype: ext4
        state: present

    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: /var/storage
        owner: nobody
        group: nobody
        mode: '0771'

    - name: Add media user
      user:
        name: media
        uid: 1100
        shell: /usr/sbin/nologin
        state: present

    - name: Create media directory
      ansible.builtin.file:
        path: /var/storage/media
        state: directory
        owner: nobody
        group: nobody
        mode: '0774'

    - name: Create tv directory
      ansible.builtin.file:
        path: /var/storage/media/tv
        state: directory
        owner: media
        group: media
        mode: '0740'

    - name: Create movies directory
      ansible.builtin.file:
        path: /var/storage/media/movies
        state: directory
        owner: media
        group: media
        mode: '0740'

    - name: Create downloads directory
      ansible.builtin.file:
        path: /var/storage/media/downloads
        state: directory
        owner: media
        group: media
        mode: '0740'

    - name: Create container-data directory
      ansible.builtin.file:
        path: /var/storage/media/container-data
        state: directory
        owner: media
        group: media
        mode: '0740'

    - name: Create prowlarr directory
      ansible.builtin.file:
        path: /var/storage/media/container-data/prowlarr
        state: directory
        owner: media
        group: media
        mode: '0740'

    - name: Create sonarr directory
      ansible.builtin.file:
        path: /var/storage/media/container-data/sonarr
        state: directory
        owner: media
        group: media
        mode: '0740'

    - name: Create radarr directory
      ansible.builtin.file:
        path: /var/storage/media/container-data/radarr
        state: directory
        owner: media
        group: media
        mode: '0740'

    - name: Create jellyfin directory
      ansible.builtin.file:
        path: /var/storage/media/container-data/jellyfin
        state: directory
        owner: media
        group: media
        mode: '0740'

    - name: Create qbittorrent directory
      ansible.builtin.file:
        path: /var/storage/media/container-data/qbittorrent
        state: directory
        owner: media
        group: media
        mode: '0740'

    - name: Create backup directory
      ansible.builtin.file:
        path: /var/storage/backup
        state: directory
        mode: '0771'

    - name: Create longhorn backup directory
      ansible.builtin.file:
        path: /var/storage/backup/longhorn
        state: directory
        mode: '0777'

    - name: Create paperless consume directory
      ansible.builtin.file:
        path: /var/storage/paperless/consume
        state: directory
        mode: '0777'

    - name: Create paperless export directory
      ansible.builtin.file:
        path: /var/storage/paperless/export
        state: directory
        mode: '0777'

    - name: Add omada user
      user:
        name: omada
        state: present
        create_home: true
        password: $6$oida$h770.OWnldE5cyRT3mcVO/dm9TwNP2HaxFCAkbred5e590HQyaaaEpVogrbY7s26DrLNZGk02r9SNIoI/4zPI1

    - name: Configure smb.conf
      template:
        src: fileserver_samba_conf.conf
        dest: /etc/samba/smb.conf
      notify: restart samba


    - name: reboot if requiered
      ansible.builtin.command: needs-restarting -r
      register: reboot_required
      failed_when: false
      changed_when: reboot_required.rc != 0
      notify:
        - reboot

  handlers:
    - name: reboot
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible"
        reboot_timeout: 3600

    - name: restart samba
      service:
        name: smb.service
        state: restarted