- hosts: k3s:workstation
  become: yes
  tasks:
    - name: install all necessary packages
      dnf:
        name: 
          - iscsi-initiator-utils
          - curl
          - wget
          - nfs-utils
          - jq
          - qemu-guest-agent
          - dnf-utils
          - cryptsetup
          - kubernetes-client
          - helm
          - git
        state: present

    - name: start qemu agent
      ansible.builtin.systemd_service:
        name: qemu-guest-agent
        state: started
        enabled: true

    - name: Create sdb mountpoint
      ansible.builtin.file:
        path: /mnt/sdb
        state: directory
      when: inventory_hostname in groups["k3s"]

    - name: Create a ext4 filesystem on /dev/sdb and check disk blocks
      community.general.filesystem:
        fstype: ext4
        dev: /dev/sdb
      when: inventory_hostname in groups["k3s"]

    - name: Mount sdb
      mount:
        path: /mnt/sdb
        src: /dev/sdb
        fstype: ext4
        state: present
      when: inventory_hostname in groups["k3s"]

    - name: Add media user
      user:
        name: media
        uid: 1100
        shell: /usr/sbin/nologin
        state: present

    - name: reboot if required
      ansible.builtin.command: needs-restarting -r
      register: reboot_required
      failed_when: false
      changed_when: reboot_required.rc != 0
      notify:
        - rebooting

  handlers:
    - name: rebooting
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible"
        reboot_timeout: 3600