- hosts: k3s:workstation
  become: yes
  tasks:
    - name: install all necessary packages
      dnf:
        name: 
          - iscsi-initiator-utils
          - curl
          - wget
          - nfs-utils
          - jq
          - qemu-guest-agent
          - dnf-utils
          - cryptsetup
          - kubernetes-client
          - helm
          - git
        state: present

    - name: start qemu agent
      ansible.builtin.systemd_service:
        name: qemu-guest-agent
        state: started
        enabled: true

    - name: reboot if requiered
      ansible.builtin.command: needs-restarting -r
      register: reboot_required
      failed_when: false
      changed_when: reboot_required.rc != 0
      notify:
        - rebooting

  handlers:
    - name: rebooting
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible"
        reboot_timeout: 3600