service:
  main:
    controller: main
    ports:
      http:
        port: &port 4533
    type: ClusterIP
controllers:
  main:
    containers:
      main:
        env:
          TZ: Etc/UTC
          ND_BASEURL: /music
          ND_SCANSCHEDULE: 1h
          ND_LOGLEVEL: info
          ND_SESSIONTIMEOUT: 24h
        image:
          pullPolicy: Always
          repository: deluan/navidrome
          tag: latest
        probes:
          liveness:
            enabled: true
            custom: true
            type: HTTP
            spec:
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
              httpGet:
                path: /
                port: *port

          readiness:
            enabled: true
            custom: true
            type: HTTP
            spec:
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
              httpGet:
                path: /
                port: *port

          startup:
            enabled: true
            custom: false
            type: HTTP
            spec:
              initialDelaySeconds: 0
              timeoutSeconds: 1
              periodSeconds: 5
              failureThreshold: 30
              httpGet:
                path: /
                port: *port
persistence:
  data:
    accessMode: ReadWriteOnce
    enabled: true
    size: 5Gi
    type: persistentVolumeClaim
  music:
    enabled: true
    path: /pool0/media/music
    server: nfs.home.007337.xyz
    type: nfs
    globalMounts:
      - path: /music/music

