service:
  main:
    controller: main
    ports:
      http:
        port: &port 8096
    type: ClusterIP
controllers:
  main:
    type: statefulset
    containers:
      main:
        env:
          TZ: Etc/UTC
        image:
          pullPolicy: Always
          repository: lscr.io/linuxserver/jellyfin
          tag: latest
        probes:
          liveness:
            enabled: true
            custom: true
            type: HTTP
            spec:
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
              httpGet:
                path: /
                port: *port

          readiness:
            enabled: true
            custom: true
            type: HTTP
            spec:
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
              httpGet:
                path: /
                port: *port

          startup:
            enabled: true
            custom: false
            type: HTTP
            spec:
              initialDelaySeconds: 0
              timeoutSeconds: 1
              periodSeconds: 5
              failureThreshold: 30
              httpGet:
                path: /
                port: *port
persistence:
  config:
    accessMode: ReadWriteOnce
    enabled: true
    size: 1Gi
    type: persistentVolumeClaim
  data:
    enabled: true
    path: /pool0/media/
    server: nfs.home.007337.xyz
    type: nfs

