controllers:
  main:
    containers:
      main:
        env:
          TZ: Etc/UTC
        image:
          pullPolicy: Always
          repository: fallenbagel/jellyseerr
          tag: latest
    strategy: Recreate
ingress:
  main:
    hosts:
      - host: media.007337.xyz
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
    tls:
      - secretName: media-007337-xyz
        hosts:
          - media.007337.xyz
persistence:
  config:
    existingClaim: jellyseerr-config
    globalMounts:
      - path: /app/config
service:
  main:
    controller: main
    ports:
      http:
        port: 5055
    type: ClusterIP
